# Generated by Django 5.2.11 on 2026-02-27 08:50

import activities.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_as_float', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True, validators=[activities.validators.validate_unit_measurement])),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('organic', models.BooleanField(default=False)),
                ('n_rate', models.FloatField(blank=True, null=True)),
                ('p_rate', models.FloatField(blank=True, null=True)),
                ('k_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('garden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gardens.garden')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.fertilizationtask')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ('-creation',),
            },
        ),
        migrations.AddField(
            model_name='fertilizationtask',
            name='fertilizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.fertilizer'),
        ),
    ]
