# Generated by Django 4.2.9 on 2024-03-11 21:16

import django.db.models.deletion
from django.db import migrations, models

import activities.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('organic', models.BooleanField(default=False)),
                ('n_rate', models.FloatField(blank=True, null=True)),
                ('p_rate', models.FloatField(blank=True, null=True)),
                ('k_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_as_float', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True, validators=[activities.validators.validate_unit_measurement])),
                ('fertilizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('fertilization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.fertilizationtask')),
                ('garden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='gardens.garden')),
            ],
            options={
                'ordering': ('creation',),
            },
        ),
    ]
