# Generated by Django 4.2.9 on 2024-03-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='fertilization',
            new_name='task',
        ),
    ]
