# Generated by Django 5.2.11 on 2026-03-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0002_watering_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawnProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grass_type', models.CharField(choices=[('cool_season', 'Saison froide (ray-grass, fétuque, pâturin)'), ('warm_season', 'Saison chaude (bermuda, zoysia, kikuyu)'), ('mixed', 'Mélange / Je ne sais pas')], default='mixed', max_length=20)),
                ('lawn_state', models.CharField(choices=[('new', 'Nouveau semis (< 6 mois)'), ('young', 'Jeune gazon (6–18 mois)'), ('established', 'Gazon établi (> 18 mois)'), ('degraded', 'Dégradé / à rénover')], default='established', max_length=20)),
                ('usage', models.CharField(choices=[('decorative', 'Décoratif — peu piétiné'), ('family', 'Familial — enfants, animaux'), ('sport', 'Sportif — terrain de jeux')], default='family', max_length=20)),
                ('sun_exposure', models.CharField(choices=[('full_sun', 'Plein soleil (> 6h/jour)'), ('partial', 'Mi-ombre (3–6h/jour)'), ('shade', 'Ombre (< 3h/jour)')], default='full_sun', max_length=20)),
                ('soil_type', models.CharField(choices=[('clay', 'Argileux (lourd, collant)'), ('loam', 'Limoneux (équilibré)'), ('sandy', 'Sableux (drainant)'), ('unknown', 'Je ne sais pas')], default='unknown', max_length=20)),
                ('goal', models.CharField(choices=[('basic', 'Propre et vert — sans se prendre la tête'), ('nice', 'Beau gazon — effort modéré'), ('perfect', 'Gazon de rêve — je suis motivé !')], default='nice', max_length=20)),
                ('has_irrigation', models.BooleanField(default=False, verbose_name="Système d'arrosage automatique")),
                ('mowing_frequency', models.PositiveSmallIntegerField(default=1, help_text='Nombre de tontes par semaine en saison de pousse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawn_profile', to='gardens.garden')),
            ],
        ),
        migrations.CreateModel(
            name='LawnAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('overall_rating', models.PositiveSmallIntegerField(choices=[(1, '😞 Très mauvais'), (2, '😕 Pas top'), (3, '🙂 Correct'), (4, '😊 Bien'), (5, '🤩 Excellent')], default=3)),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of issue keys from ISSUE_CHOICES')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawn_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='weather.lawnprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
