# Generated by Django 5.2.11 on 2026-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute')], default=2),
        ),
    ]
