# Generated by Django 5.2.11 on 2026-03-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_planttask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttask',
            name='source',
            field=models.CharField(choices=[('manual', 'Ajout manuel'), ('suggestion', 'Conseil automatique')], default='manual', help_text='How this task was created', max_length=20),
        ),
    ]
