# Generated by Django 5.2.11 on 2026-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='watering_profile',
            field=models.CharField(choices=[('standard', '🌿 Standard — beau jardin, arrosage équilibré'), ('eco', '💧 Éco-responsable — économe en eau, gazon soigné'), ('resilient', '🌾 Résilient — accepte la dormance en été'), ('laissez_faire', "🍃 Laisser-faire — pas d'arrosage, la nature décide"), ('pro', '⛳ Greenkeeper pro — gazon de golf, tolérance zéro')], default='standard', max_length=20),
        ),
    ]
